
services:
  db:
    image: postgres:17
    container_name: airlines_data_base
    environment:
      POSTGRES_USER: yuliia
      POSTGRES_PASSWORD: yuliia
      POSTGRES_DB: airlines_data_base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot_network

volumes:
  postgres_data:

networks:
  springboot_network:
